### PR TITLE
Metadata is passed in the files, not the body_arguments

### PR DESCRIPTION
**Pull request by akofink**
@jhjaggars

### CODE REVIEW

**Comment by beav** [comment]
@akofink can you give more info on how to repro the issue?

**Comment by akofink** [comment]
@beav In the client, I put a breakpoint [here](https://github.com/RedHatInsights/insights-core/blob/master/insights/client/connection.py#L736), reran `sudo sh lay-the-eggs.sh`, and then tried uploading a scap report: `sudo BYPASS_GPG=true insights-client --no-gpg --payload ~/rhel7-content_profile_common.xml --content-type application/vnd.redhat.compliance.something+tgz"`. You should see metadata in `files['metadata']` in pdb.

**Comment by akofink** [comment]
There was an issue with the previous implementation. I've just updated it (and tested it properly this time).

**Comment by lphiri** [comment]
@akofink  @beav  details escape me, but there was a reason @SteveHNH was looking in body_arguments. 
What version of tornado are you running ?  Maybe we should look in both places?
https://www.tornadoweb.org/en/stable/httputil.html#tornado.httputil.HTTPServerRequest.body_arguments)

**Comment by akofink** [comment]
Looks like 5.1.1? https://github.com/RedHatInsights/insights-upload/blob/master/Pipfile.lock#L148

**Comment by lphiri** [comment]
@afonik that is interesting.  Are you running your test from master?
I believe the uploads service is expecting the client to send the equivalent of this:
`curl -k -vvvv --cert /etc/pki/consumer/cert.pem --key /etc/pki/consumer/key.pem  -F "file=@/root/test.tar.gz;type=application/vnd.redhat.testareno.something+tgz"   -F "metadata=@/root/meta.json;type=application/json "https://<HOST>/r/insights/platform/api/v1/upload`

I know this was broken in the client and had to reverted recently:

https://github.com/RedHatInsights/insights-core/commit/59d240a4c7d1d7d836e8ad0b846c3046beed5f05

**Comment by akofink** [comment]
Yes, I'm running from master. I have slightly modified insights-core for testing with a local insights-upload, but other than that, it's master:

```diff
diff --git a/insights/client/connection.py b/insights/client/connection.py
index 0a4ddb0f..82b7e3a3 100644
--- a/insights/client/connection.py
+++ b/insights/client/connection.py
@@ -733,6 +733,9 @@ class InsightsConnection(object):
             headers = {'x-rh-collection-time': str(duration)}
         else:
             headers = {}
+            if 'compliance' in content_type:
+                headers['x-rh-insights-request-id'] = data_collected.split('/')[-1]
+                headers['x-rh-identity'] = '<my x-rh-identity>'
             files['metadata'] = c_facts

         files['file'] = (file_name, open(data_collected, 'rb'), content_type)
```

**Comment by SteveHNH** [comment]
@akofink I'm going to check this one out and see how it goes. I tried metadata in the files early on and it seemed that JSON was automatically fed to body_arguements rather than files. It drove me crazy for a while until I finally figured that out. I'll let you know how it goes

**Comment by SteveHNH** [comment]
@akofink I think @lphiri is correct in that the proper implementation would be to look in both places. We know for sure that there are methods out in the wild that are using it as is and are successfully passing metadata through. But I have no problems supporting getting the metadata out of `files` if it exists there. Would you be willing to update this PR to look in both places and see which one has the metadata?

**Comment by akofink** [comment]
Sure, no problem

**Comment by akofink** [comment]
Updated

**Pull request merged**
